# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

# command to install dependencies, e.g. pip install -r requirements.txt
install: pip install tox-travis

# command to run tests, e.g. python setup.py test
script: tox
language: python

jobs:
  include:
    - os: linux
      arch: amd64
      dist: focal
      python: 2.7
    - os: linux
      arch: amd64
      dist: focal
      python: 3.5
    - os: linux
      arch: amd64
      dist: focal
      python: 3.6
    - os: linux
      arch: amd64
      dist: focal
      python: 3.7
    - os: linux
      arch: amd64
      dist: focal
      python: 3.8
    - os: linux
      arch: amd64
      dist: focal
      python: 3.9
    - os: linux
      arch: amd64
      dist: focal
      python: 3.10-dev

    - os: linux
      arch: arm64
      dist: bionic
      python: 2.7
    - os: linux
      arch: arm64
      dist: focal
      python: 3.5
    - os: linux
      arch: arm64
      dist: focal
      python: 3.6
    - os: linux
      arch: arm64
      dist: focal
      python: 3.7
    - os: linux
      arch: arm64
      dist: focal
      python: 3.8
    - os: linux
      arch: arm64
      dist: focal
      python: 3.9
    - os: linux
      arch: arm64
      dist: focal
      python: 3.10-dev

    - os: linux
      arch: ppc64le
      dist: bionic
      python: 2.7
    - os: linux
      arch: ppc64le
      dist: focal
      python: 3.5
    - os: linux
      arch: ppc64le
      dist: focal
      python: 3.6
    - os: linux
      arch: ppc64le
      dist: bionic
      python: 3.7
    - os: linux
      arch: ppc64le
      dist: focal
      python: 3.8
    - os: linux
      arch: ppc64le
      dist: focal
      python: 3.9

    - os: linux
      arch: s390x
      dist: bionic
      python: 2.7
    - os: linux
      arch: s390x
      dist: focal
      python: 3.5
    - os: linux
      arch: s390x
      dist: focal
      python: 3.6
    - os: linux
      arch: s390x
      dist: bionic
      python: 3.7
    - os: linux
      arch: s390x
      dist: focal
      python: 3.8
    - os: linux
      arch: s390x
      dist: focal
      python: 3.9

    - os: osx
      language: generic
      osx_image: xcode12.2
      python: 2.7
      env: PYTHON=2.7
    - os: osx
      language: generic
      osx_image: xcode12.2
      python: 3.5
      env: PYTHON=3.5
    - os: osx
      language: generic
      osx_image: xcode12.2
      python: 3.6
      env: PYTHON=3.6
    - os: osx
      language: generic
      osx_image: xcode12.2
      python: 3.7
      env: PYTHON=3.7
    - os: osx
      language: generic
      osx_image: xcode12.2
      python: 3.8
      env: PYTHON=3.8
    - os: osx
      language: generic
      osx_image: xcode12.2
      python: 3.9
      env: PYTHON=3.9
    - os: osx
      language: generic
      osx_image: xcode12.2
      python: 3.10-dev
      env: PYTHON=3.10-dev
