# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

matrix:
  include:
    - os: linux
      language: python
      dist: xenial
      python: 2.7
    - os: linux
      language: python
      dist: xenial
      python: 3.5
    - os: linux
      language: python
      dist: xenial
      python: 3.6
    - os: linux
      language: python
      dist: xenial
      python: 3.7
    - os: linux
      language: python
      dist: xenial
      python: 3.8-dev
    - os: linux
      language: python
      dist: xenial
      python: nightly
    - os: osx
      language: generic
      env: PYTHON=2.7
    - os: osx
      language: generic
      env: PYTHON=3.5
    - os: osx
      language: generic
      env: PYTHON=3.6
    - os: osx
      language: generic
      env: PYTHON=3.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox-travis

# command to run tests, e.g. python setup.py test
script: tox
